name: tokenspice_continuous_integration

on:
  push:
    branches: [ action_tests ]
  pull_request:
    branches: [ action_tests ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.8, 3.9 ]


    steps:
      - uses: actions/checkout@v2

      - name: Set up Python {{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest numpy
          if [ -f requirements.txt ]; 
            then pip install -r requirements.txt; 
            echo "Requirements.txt found! ( thnx BK :* )"
          fi
          
      - name: Find out what the directory structure looks like
        run: |
          pwd
          tree
          
      - name: Executing Python Ganache script
        run: |
          ./ganache.py

      - name: Check Node version on this machine.
        run: |
          npm -v

      - name: Clone Ocean Protocol Contracts and Install them
        uses: actions/checkout@master
        with:
          name: oceanprotocol/contracts
          ref: refs/heads/release
